### ISSUE TITLE
Sikeres akcióról visszajelzések

### ISSUE THREAD

**Issue by tomzorz** [tomzorz/viaual01#15]
Ezzel a TempData mókával lenne érdemes megcsinálni: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x#tempdata

Minden akciónál (pl.: group accept, státusz jelzés stb...) be kéne ide írni egy user-friendly üzenetet (pl.: "Sikeresen mondtad, h nem tudsz menni most enni.") majd ezt az üzenetet innen kiolvasni és egy bootstrap alert template-ben megjeleníteni. 

Ennek a template-es kódját a _layout-os cuccba kéne rakni és akkor nem kell minden oldalon egyesével megcsinálni :)

**Comment by bencetaylor** [comment]
Végül nem a _layout-ba raktam, hanem az index és details oldalakra
